// SPDX-FileCopyrightText: Olivier Cléro <oclero@hotmail.com>
// SPDX-License-Identifier: MIT

#include <oclero/qlementine/icons/QlementineIcons.hpp>

#include <mutex>
#include <unordered_map>

#include <qglobal.h>
#include <QIcon>

// This must be done outside of any namespace.
void qlementineIconThemeInitialization() {
  // Loads the QRC content.
  // --- This part is generated by scripting. Don't modify.
  Q_INIT_RESOURCE(qlementine_icons_12_action);
  Q_INIT_RESOURCE(qlementine_icons_12_misc);
  Q_INIT_RESOURCE(qlementine_icons_12_navigation);
  Q_INIT_RESOURCE(qlementine_icons_16_action);
  Q_INIT_RESOURCE(qlementine_icons_16_audio);
  Q_INIT_RESOURCE(qlementine_icons_16_brand);
  Q_INIT_RESOURCE(qlementine_icons_16_document);
  Q_INIT_RESOURCE(qlementine_icons_16_file);
  Q_INIT_RESOURCE(qlementine_icons_16_food);
  Q_INIT_RESOURCE(qlementine_icons_16_hardware);
  Q_INIT_RESOURCE(qlementine_icons_16_instruments);
  Q_INIT_RESOURCE(qlementine_icons_16_media);
  Q_INIT_RESOURCE(qlementine_icons_16_misc);
  Q_INIT_RESOURCE(qlementine_icons_16_navigation);
  Q_INIT_RESOURCE(qlementine_icons_16_page);
  Q_INIT_RESOURCE(qlementine_icons_16_shape);
  Q_INIT_RESOURCE(qlementine_icons_16_shopping);
  Q_INIT_RESOURCE(qlementine_icons_16_software);
  Q_INIT_RESOURCE(qlementine_icons_16_text);
  Q_INIT_RESOURCE(qlementine_icons_32_file);
  Q_INIT_RESOURCE(qlementine_icons_32_misc);
  Q_INIT_RESOURCE(qlementine_icons_32_shape);
  // ---

  // Registers the icon theme.
  QIcon::setFallbackSearchPaths(QIcon::fallbackSearchPaths() << ":/qlementine/icons");
}

namespace oclero::qlementine::icons {
std::once_flag qlementineOnceFlag;

std::unordered_map<QString, QString> freeDesktopMapping{
  // clang-format off
  { "edit-undo", "16/action/undo" },
  { "edit-redo", "16/action/redo" },
  // clang-format on
};

void initializeIconTheme() {
  std::call_once(qlementineOnceFlag, qlementineIconThemeInitialization);
}

QString fromFreeDesktop(const QString& freeDesktopName) {
  const auto it = freeDesktopMapping.find(freeDesktopName);
  return it != freeDesktopMapping.end() ? it->second : QString();
}
} // namespace oclero::qlementine::icons
