// SPDX-FileCopyrightText: Olivier Cléro <oclero@hotmail.com>
// SPDX-License-Identifier: MIT

// NB: This file is generated by Python. If you want to make some changes, edit the template.

#pragma once

#include <array>

namespace oclero::qlementine::icons {

enum class $enum_name {
  None = 0,
  $enum_keys,
};

inline const char* iconPath($enum_name id) {
  static constexpr std::array<const char*, $enum_count> icons{
    "",
    $array_items,
  };

  return icons[static_cast<typename std::underlying_type<$enum_name>::type>(id)];
}
} // namespace oclero::qlementine::icons
