// SPDX-FileCopyrightText: Olivier Cléro <oclero@hotmail.com>
// SPDX-License-Identifier: MIT

// NB: This file is generated by Python. If you want to make some changes, edit the template.

#pragma once

#include <array>

namespace oclero::qlementine::icons {

enum class Icons32 {
  None = 0,
  File_FolderOpen,
  Hardware_Drive,
  Hardware_Hdd,
  Hardware_PhotoCamera,
  Hardware_PhotoCameraCrossed,
  Misc_Info,
  Misc_Question,
  Misc_Spam,
  Misc_Success,
  Misc_Warning,
  Shape_CircleFilled,
  Shape_OctogonFilled,
  Shape_TriangleFilled,
};

inline const char* iconPath(Icons32 id) {
  static constexpr std::array<const char*, 14> icons{
    "",
    ":/qlementine/icons/32/file/folder-open.svg",
    ":/qlementine/icons/32/hardware/drive.svg",
    ":/qlementine/icons/32/hardware/hdd.svg",
    ":/qlementine/icons/32/hardware/photo-camera.svg",
    ":/qlementine/icons/32/hardware/photo-camera-crossed.svg",
    ":/qlementine/icons/32/misc/info.svg",
    ":/qlementine/icons/32/misc/question.svg",
    ":/qlementine/icons/32/misc/spam.svg",
    ":/qlementine/icons/32/misc/success.svg",
    ":/qlementine/icons/32/misc/warning.svg",
    ":/qlementine/icons/32/shape/circle-filled.svg",
    ":/qlementine/icons/32/shape/octogon-filled.svg",
    ":/qlementine/icons/32/shape/triangle-filled.svg",
  };

  return icons[static_cast<typename std::underlying_type<Icons32>::type>(id)];
}
} // namespace oclero::qlementine::icons
