// SPDX-FileCopyrightText: Olivier Cléro <oclero@hotmail.com>
// SPDX-License-Identifier: MIT

// NB: This file is generated by Python. If you want to make some changes, edit the template.

#pragma once

#include <array>

namespace oclero::qlementine::icons {

enum class Icons12 {
  None = 0,
  Action_Close,
  Action_Minus,
  Action_Plus,
  Misc_Zoom,
  Navigation_ArrowsLeftRight,
  Navigation_ArrowsUpDown,
  Navigation_ChevronDown,
  Navigation_ChevronLeft,
  Navigation_ChevronRight,
  Navigation_ChevronUp,
};

inline const char* iconPath(Icons12 id) {
  static constexpr std::array<const char*, 11> icons{
    "",
    ":/qlementine/icons/12/action/close.svg",
    ":/qlementine/icons/12/action/minus.svg",
    ":/qlementine/icons/12/action/plus.svg",
    ":/qlementine/icons/12/misc/zoom.svg",
    ":/qlementine/icons/12/navigation/arrows-left-right.svg",
    ":/qlementine/icons/12/navigation/arrows-up-down.svg",
    ":/qlementine/icons/12/navigation/chevron-down.svg",
    ":/qlementine/icons/12/navigation/chevron-left.svg",
    ":/qlementine/icons/12/navigation/chevron-right.svg",
    ":/qlementine/icons/12/navigation/chevron-up.svg",
  };

  return icons[static_cast<typename std::underlying_type<Icons12>::type>(id)];
}
} // namespace oclero::qlementine::icons
